name: Publish

on:
  push:
    branches: [master]

env:
  NPM_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run: yarn install
      - run: yarn run lerna publish from-package --yes
